steps:

# Buid Prometheus
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/$_PROJECT_ID/plantmon/prometheus:latest', '.' ]
  dir: 'prometheus/'
  id: 'prometheus_build'
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$_PROJECT_ID/plantmon/prometheus:latest']
  id: 'prometheus_push'
  waitFor: ['prometheus_build']

# Buid Grafana
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/$_PROJECT_ID/plantmon/grafana:latest', '.' ]
  dir: 'grafana/'
  id: 'grafana_build'
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$_PROJECT_ID/plantmon/grafana:latest']
  id: 'grafana_push'
  waitFor: ['grafana_build']