steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/fresh-replica-355617/plantmon/prometheus', '.' ]
  dir: '/prometheus/'
  id: 'prometheus_build'
  waitFor: ['-']

images:
  - 'us-central1-docker.pkg.dev/fresh-replica-355617/plantmon/prometheus'