steps:

# Buid metric publisher
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/$_PROJECT_ID/plantmon/metric_publisher:latest', '.' ]
  dir: 'pubsub/metric_publisher/'
  id: 'metric_publisher'
  waitFor: ['-']

# Push metric publisher
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$_PROJECT_ID/plantmon/metric_publisher:latest']
  id: 'metric_publisher_push'
  waitFor: ['metric_publisher']

# Deploy prometheus to cloud run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 
         'deploy', 'prometheus', 
         '--image', 'us-central1-docker.pkg.dev/$_PROJECT_ID/plantmon/metric_publisher:latest',
         '--region', 'us-central1',
         '--port', '8080']
  id: 'deploy_metric_publisher'
  waitFor: ['metric_publisher_push']
